//! Unit tests for the Keccak256 Permute chip.
//!
//! These tests verify that the keccak permute chip correctly processes
//! keccak events generated by RV64 ELF programs.

use crate::{
    chips::tests::{
        find_record_with_events, run_extra_records, test_rv64_emulate,
        test_rv64_prove_and_verify_chunk,
    },
    compiler::riscv::compiler::{Compiler, SourceType},
    configs::stark_config::KoalaBearPoseidon2,
    emulator::{
        riscv::syscalls::{
            precompiles::{KeccakPermuteEvent, PrecompileEvent},
            SyscallCode,
        },
        stdin::EmulatorStdin,
    },
    instances::chiptype::riscv_chiptype::RiscvChipType,
    machine::chip::MetaChip,
};
use p3_koala_bear::KoalaBear;

use crate::compiler::riscv::program::Program;

const TINY_KECCAK_ELF: &[u8] =
    include_bytes!("../../../../../perf/bench_data/rv64/tiny-keccak-elf");
const SHA3_ELF: &[u8] = include_bytes!("../../../../../perf/bench_data/rv64/sha3-elf");

/// Helper: extract `KeccakPermuteEvent`s from a record.
fn extract_keccak_events(
    record: &crate::emulator::riscv::record::EmulationRecord,
) -> Vec<&KeccakPermuteEvent> {
    record
        .get_precompile_events(SyscallCode::KECCAK_PERMUTE)
        .iter()
        .filter_map(|(_, event)| {
            if let PrecompileEvent::KeccakPermute(e) = event {
                Some(e)
            } else {
                None
            }
        })
        .collect()
}

// ──────────────────────────────────────────────────────────────
// Test 1: tiny-keccak ELF — prove/verify
// ──────────────────────────────────────────────────────────────

#[test]
fn test_rv64_keccak_tiny_keccak_elf() {
    let compiler =
        Compiler::new(SourceType::RISCV, TINY_KECCAK_ELF).expect("failed to compile tiny-keccak");
    let program = compiler.compile();

    let mut stdin_builder = EmulatorStdin::<Program, Vec<u8>>::new_builder::<KoalaBearPoseidon2>();
    // Guest calls read_vec(), provide a short preimage
    stdin_builder.write(&vec![0x61u8, 0x62, 0x63]); // "abc"
    let (stdin, _) = stdin_builder.finalize();

    let all_records = test_rv64_emulate(program.clone(), stdin);
    let mut record = find_record_with_events(all_records, SyscallCode::KECCAK_PERMUTE);

    let keccak_events = extract_keccak_events(&record);
    assert!(
        !keccak_events.is_empty(),
        "Should have keccak permute events"
    );
    println!("Keccak permute events: {}", keccak_events.len());

    let chips = vec![
        MetaChip::test_no_lookup(RiscvChipType::<KoalaBear>::Program(Default::default())),
        MetaChip::test_no_lookup(RiscvChipType::<KoalaBear>::KeecakP(Default::default())),
        MetaChip::test_no_lookup(RiscvChipType::<KoalaBear>::MemoryLocal(Default::default())),
    ];

    run_extra_records(&chips, &mut record);
    test_rv64_prove_and_verify_chunk(program, chips, record);
}

// ──────────────────────────────────────────────────────────────
// Test 2: sha3 ELF — prove/verify
// ──────────────────────────────────────────────────────────────

#[test]
fn test_rv64_keccak_sha3_elf() {
    let compiler = Compiler::new(SourceType::RISCV, SHA3_ELF).expect("failed to compile sha3");
    let program = compiler.compile();

    let mut stdin_builder = EmulatorStdin::<Program, Vec<u8>>::new_builder::<KoalaBearPoseidon2>();
    stdin_builder.write(&vec![0x61u8, 0x62, 0x63]); // "abc"
    let (stdin, _) = stdin_builder.finalize();

    let all_records = test_rv64_emulate(program.clone(), stdin);
    let mut record = find_record_with_events(all_records, SyscallCode::KECCAK_PERMUTE);

    let keccak_events = extract_keccak_events(&record);
    assert!(
        !keccak_events.is_empty(),
        "Should have keccak permute events"
    );
    println!("Keccak permute events: {}", keccak_events.len());

    let chips = vec![
        MetaChip::test_no_lookup(RiscvChipType::<KoalaBear>::Program(Default::default())),
        MetaChip::test_no_lookup(RiscvChipType::<KoalaBear>::KeecakP(Default::default())),
        MetaChip::test_no_lookup(RiscvChipType::<KoalaBear>::MemoryLocal(Default::default())),
    ];

    run_extra_records(&chips, &mut record);
    test_rv64_prove_and_verify_chunk(program, chips, record);
}

// ──────────────────────────────────────────────────────────────
// Test 3: Event data validation
// ──────────────────────────────────────────────────────────────

#[test]
fn test_rv64_keccak_event_data_validation() {
    use tiny_keccak::keccakf;

    let compiler =
        Compiler::new(SourceType::RISCV, TINY_KECCAK_ELF).expect("failed to compile tiny-keccak");
    let program = compiler.compile();

    let mut stdin_builder = EmulatorStdin::<Program, Vec<u8>>::new_builder::<KoalaBearPoseidon2>();
    stdin_builder.write(&vec![0x61u8, 0x62, 0x63]);
    let (stdin, _) = stdin_builder.finalize();

    let all_records = test_rv64_emulate(program.clone(), stdin);
    let record = find_record_with_events(all_records, SyscallCode::KECCAK_PERMUTE);
    let keccak_events = extract_keccak_events(&record);

    assert!(
        !keccak_events.is_empty(),
        "Should have keccak permute events"
    );

    for (idx, event) in keccak_events.iter().enumerate() {
        // Verify read/write records count == 25 (u64 dword upgrade)
        assert_eq!(
            event.state_read_records.len(),
            25,
            "Event {idx}: state_read_records should have 25 dword records, got {}",
            event.state_read_records.len()
        );
        assert_eq!(
            event.state_write_records.len(),
            25,
            "Event {idx}: state_write_records should have 25 dword records, got {}",
            event.state_write_records.len()
        );

        // Verify post_state == keccakf(pre_state)
        let mut expected = event.pre_state;
        keccakf(&mut expected);
        assert_eq!(
            event.post_state, expected,
            "Event {idx}: post_state != keccakf(pre_state)"
        );

        // Verify state_addr is reasonable (>= MIN_MAIN_MEMORY_ADDR)
        assert!(
            event.state_addr >= 0x100,
            "Event {idx}: state_addr 0x{:x} too low",
            event.state_addr
        );

        // Verify state_addr is 8-byte aligned (required for dword access)
        assert_eq!(
            event.state_addr % 8,
            0,
            "Event {idx}: state_addr 0x{:x} not 8-byte aligned",
            event.state_addr
        );

        println!(
            "Event {idx}: addr=0x{:x}, reads={}, writes={}, keccakf verified ✓",
            event.state_addr,
            event.state_read_records.len(),
            event.state_write_records.len(),
        );
    }
}

#[test]
fn test_keccak_permute_chip_simple_eval() {
    use crate::machine::{
        builder::PublicValuesBuilder, chip::ChipBehavior, folder::SymbolicConstraintFolder,
    };
    use p3_air::{Air, BaseAir};
    use p3_koala_bear::KoalaBear;

    let chip: super::KeccakPermuteChip<KoalaBear> = super::KeccakPermuteChip::default();
    let preprocessed_width = chip.preprocessed_width();
    let width = chip.width();
    let mut builder = SymbolicConstraintFolder::new(preprocessed_width, width);
    chip.eval(&mut builder);

    assert_eq!(builder.num_constraints(), 3721);
    assert_eq!(builder.public_values().len(), 119);
    assert_eq!(builder.num_lookups(), 277);
}
