[package]
name = "patch-test-ecdsa-core"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[dependencies]
# pico-sdk = { git = "https://github.com/brevis-network/pico", branch = "rv64" }
pico-sdk.workspace = true
alloy-primitives = "0.8.19"
k256 = { git = "https://github.com/brevis-network/elliptic-curves", branch = "k256-0.13.4-rv64" }
tiny-keccak = { git = "https://github.com/brevis-network/tiny-keccak", features = ["keccak"], branch = "patch-v1.0.0-rv64" }
