// Constants for instruction encoding
pub const SHIFT_MASK: u32 = 0x1f; // Mask for shift amounts (5 bits)
pub const BYTES_PER_WORD: u32 = 4;
pub const CLOCK_INCREMENT_PER_INSN: u32 = 4;

/// Safety margin for fast-path clock threshold.
/// Must account for max block size that could be executed before next check.
/// DEFAULT_MAX_BLOCK_INSTRUCTIONS = 2048, so max block is 2048 * 4 = 8192 cycles.
/// Add some buffer for syscalls and edge cases.
pub const FAST_PATH_CLK_MARGIN: u32 = 10000;

/// Safety margin for fast-path event threshold.
/// Must account for events generated by one max block.
/// Each instruction can generate ~1-2 events in worst case.
/// DEFAULT_MAX_BLOCK_INSTRUCTIONS = 2048, so max events per block ~4096.
pub const FAST_PATH_EVENT_MARGIN: usize = 5000;
