[package]
name = "pico-compiler"
version = "0.1.0"
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
# p3
p3-field.workspace = true

serde.workspace = true

