[package]
name = "pico-cli"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[build-dependencies]
vergen.workspace = true

[dependencies]
anyhow.workspace = true
cargo_metadata.workspace = true
clap.workspace = true
dirs.workspace = true
env_logger.workspace = true
futures.workspace = true
hex.workspace = true
indicatif.workspace = true
log.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
pico-sdk.workspace = true
pico-vm.workspace = true
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
target-lexicon.workspace = true
tokio.workspace = true
yansi.workspace = true
