//! AOT snapshot emulator factory.
//!
//! This is the cpu-u64 variant — its `AotFactory` signature intentionally
//! diverges from the gpu-u64 sibling: it does NOT take an
//! `Arc<RecordFinalPvsState>`. Cpu-u64 has no `Condvar`-based cross-thread
//! waiter for the final committed digest; the sequencer derives the public
//! values from replayed worker records via
//! `EmulationDeferredState::update_public_values`. A future "unify with
//! gpu-u64" pass should reconcile this divergence.

use crate::{
    compiler::riscv::program::Program,
    emulator::{
        opts::EmulatorOpts,
        riscv::{riscv_emulator::EmulationError, state::RiscvEmulationState},
    },
    machine::report::EmulationReport,
};
use alloc::{boxed::Box, sync::Arc};
use std::sync::OnceLock;

pub trait AotSnapshotEmulator: Send {
    fn next_state_batch(
        &mut self,
    ) -> Result<(RiscvEmulationState, EmulationReport), EmulationError>;
    fn cycles(&self) -> u64;
    fn get_pv_stream(&mut self) -> Vec<u8>;
}

type AotFactory = fn(Arc<Program>, Vec<Vec<u8>>, EmulatorOpts) -> Box<dyn AotSnapshotEmulator>;

/// Process-wide AOT factory slot.
///
/// Uses `OnceLock` because the chunk crates generated by
/// `pico-aot-codegen` link their symbols into the host binary statically,
/// so a process can drive at most one AOT build in practice. Registering a
/// second factory is silently ignored; callers that expect to swap factories
/// across runs should assume this is a one-way switch.
static AOT_FACTORY: OnceLock<AotFactory> = OnceLock::new();

pub fn register_aot_factory(factory: AotFactory) {
    let _ = AOT_FACTORY.set(factory);
}

pub fn is_aot_factory_registered() -> bool {
    AOT_FACTORY.get().is_some()
}

pub fn create_aot_emulator(
    program: Arc<Program>,
    input_stream: Vec<Vec<u8>>,
    opts: EmulatorOpts,
) -> Option<Box<dyn AotSnapshotEmulator>> {
    AOT_FACTORY
        .get()
        .map(|factory| factory(program, input_stream, opts))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::emulator::opts::EmulatorOpts;

    // OnceLock is process-wide and cannot be reset between tests; all
    // assertions that observe registration share a single test fn.
    struct DummyAot;
    impl AotSnapshotEmulator for DummyAot {
        fn next_state_batch(
            &mut self,
        ) -> Result<(RiscvEmulationState, EmulationReport), EmulationError> {
            unreachable!("dummy AOT emulator never invoked in tests")
        }
        fn cycles(&self) -> u64 {
            0
        }
        fn get_pv_stream(&mut self) -> Vec<u8> {
            Vec::new()
        }
    }

    fn dummy_factory(
        _p: Arc<Program>,
        _i: Vec<Vec<u8>>,
        _o: EmulatorOpts,
    ) -> Box<dyn AotSnapshotEmulator> {
        Box::new(DummyAot)
    }

    #[test]
    fn factory_registration_and_creation() {
        assert!(!is_aot_factory_registered());

        register_aot_factory(dummy_factory);
        assert!(is_aot_factory_registered());

        // Registering a factory does NOT change EmulatorOpts::default() —
        // callers must opt in explicitly via `.with_snapshot_main(Aot)`.
        assert_eq!(
            EmulatorOpts::default().snapshot_main,
            crate::emulator::opts::SnapshotMainMode::Interpreter
        );

        // Factory is callable.
        let prog = Arc::new(Program::default());
        let boxed = create_aot_emulator(prog, Vec::new(), EmulatorOpts::default());
        assert!(boxed.is_some());
    }
}
